name: football-predictor
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9.7
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - numpy=1.20.3
  - pandas=1.3.4
  - seaborn=0.11.2
  - tqdm=4.62.3
